from typing import Optional, Union

# This file was hand made, based directly of PyGObject __init__.py

def check_version(version: Union[str, tuple[int, int, int]]) -> None: ...
def require_version(namespace: str, version: str) -> None: ...
def require_versions(requires: dict[str, str]) -> None: ...
def get_required_version(namespace: str) -> None: ...
def require_foreign(namespace: str, symbol: Optional[str] = None) -> None: ...
